minQuestionTitle: 20
minQuestionContent: 50
minTagsPerQuestion: 1
maxTagsPerQuestion: 5
minAnswerTitle: 50
minAnswerContent: 50
minComment: 10
canCreateTags: 'false'
minLengthPass: 6
minLengthLogin: 6
reCaptcha_public: 6Ld2fsMSAAAAAEPkx8m-Fb0FjlC0WxxZ3JPTIc_I
reCaptcha_private: 6Ld2fsMSAAAAANlwFbgd6qndnP8-A5LhV9-wvWfV
questionsPerPage: 15
questionsPerPageOnFiche: 6
sphinx_host: 127.0.0.1
sphinx_port: 9312
questionsPerPageSearch: 10

